// Ambient binding types for the connector Worker.
//
// `cloudflare:test` types its `env` export as `Cloudflare.Env`, and the Workers
// runtime types declare that namespace as an empty interface for projects to
// merge into. Hand-written rather than generated by `wrangler types` so there is
// no generated file to drift; keep it in step with wrangler.jsonc's bindings.
//
// src/worker.ts re-exports this as its `Env`, so the shape is declared once.
declare namespace Cloudflare {
  interface Env {
    MCP_OBJECT: DurableObjectNamespace;
    OAUTH_KV: KVNamespace;
    MEDIA_BUCKET: R2Bucket;
    GEMINI_API_KEY?: string;
    /**
     * Public base URL of MEDIA_BUCKET (R2 public dev URL or custom domain), no
     * trailing slash. Unset → generated media is still stored, but the result
     * reports honest `r2://bucket/key` refs instead of URLs that would 404.
     */
    MEDIA_PUBLIC_BASE_URL?: string;
  }
}
